version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: tradingbot_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=TradingBot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tradingbot_network

  seq:
    image: datalust/seq:latest
    container_name: tradingbot_seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    volumes:
      - seq_data:/data
    networks:
      - tradingbot_network

  backend:
    build:
      context: ./backend
      dockerfile: TradingBot/Dockerfile
    container_name: tradingbot_api
    depends_on:
      - postgres
      - seq
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=TradingBot;User Id=postgres;Password=yourpassword;
      - Seq__ServerUrl=http://seq:80
    networks:
      - tradingbot_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tradingbot_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - tradingbot_network

volumes:
  postgres_data:
  seq_data:

networks:
  tradingbot_network:
    driver: bridge 